### ISSUE TITLE
error namespace load failed for "tidyverse"

### ISSUE THREAD

**Issue by talban14** [tidyverse/tidyverse#133]
I've been running tidyverse for a while but today I'm having issues getting it to load after updatedin to R 3.5  and also updating R studio.  I've tried reinstalling them multiple times with no luck in changing this error message.  I've also tried removing and re-installing the tidyverse package but still no luck.  I'm able to load other packages just fine. 

```
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in namespaceExport(ns, exports):
 undefined exports: %s!=%, %s!==%, %s+%, %s<%, %s<=%, %s==%, %s===%, %s>%, %s>=%, %stri!=%, %stri!==%, %stri+%, %stri<%, %stri<=%, %stri==%, %stri===%, %stri>%, %stri>=%, stri_datetime_add<-, stri_sub<-, stri_subset<-, stri_subset_charclass<-, stri_subset_coll<-, stri_subset_fixed<-, stri_subset_regex<-, stri_c, stri_c_list, stri_cmp, stri_cmp_eq, stri_cmp_equiv, stri_cmp_ge, stri_cmp_gt, stri_cmp_le, stri_cmp_lt, stri_cmp_neq, stri_cmp_nequiv, stri_compare, stri_conv, stri_count, stri_count_boundaries, stri_count_charclass, stri_count_coll, stri_count_fixed, stri_count_regex, stri_count_words, stri_datetime_add, stri_datetime_create, stri_datetime_fields, stri_datetime_format, stri_datetime_fstr, stri_datetime_now, stri_datetime_parse, stri_datetime_symbols, stri_detect, stri_detect_charclass, stri_detect_coll, stri_detect_fixed, stri_detect_regex, stri_dup, stri_duplicated, stri_duplicated_any, 
```

**Comment by batpigandme** [comment]
Have you tried reinstalling and loading the [stringi](https://github.com/gagolews/stringi/blob/738f4b1ab5845ba2879f3d5fff2e60767ea691e5/NAMESPACE) package? All of these functions are from that package, which is imported by stringr (one of the tidyverse packages):
https://github.com/tidyverse/stringr/blob/master/NAMESPACE
In the event that you can't get stringi or stringr installed, you should file this issue in the stringr repo, since the tidyverse package is just a wrapper around its constituent packages and the changes would need to be addressed over there.

Hopefully this helps!
