### ISSUE TITLE
Error involving rvest and xml2

### ISSUE THREAD

**Issue by cryptic0** [tidyverse/tidyverse#134]
R version 3.5
MacOSX 10.13.2
Unable to install tidyverse, and the following two packages separately.

ERROR: dependencies ‘rvest’, ‘xml2’ are not available for package ‘tidyverse’

**Comment by batpigandme** [comment]
When happens if you try to install the packages individually?

**Comment by batpigandme** [comment]
[rvest](https://CRAN.R-project.org/package=rvest) depends on [xml2](https://cran.r-project.org/web/packages/xml2/index.html) (xml2 doesn't depend on rvest), if you're having trouble with your xml2 installation (which sounds likely), could you please file an issue in the [xml2](https://github.com/r-lib/xml2) repo? (I recommend searching the existing issues for your error message first, open or closed, as there tend to be common issues/solutions in there 👍).

Since the tidyverse package just wraps the component packages, I'm going to close this issue, as any related issues will be resolved in the individual package libraries!
