### ISSUE TITLE
Trouble installing tidyverse on macOS 10.13.4 (High Sierra) - solved by xcode-select --install

### ISSUE THREAD

**Issue by gvwilson** [tidyverse/tidyverse#154]
1. Uninstall all versions of R and RStudio from MacBook Air.
2. Upgrade to macOS 10.13.4 (High Sierra).
3. Install RStudio 1.1.456.
4. `which r` from command line finds nothing (so I believe there are no conflicting version of R in play).
5. Launch RStudio.
6. `install.packages("tidyverse")` in RStudio fails trying to install `xml2` because `libxml-2.0` is not found.
7. `brew install libxml2` from command line does not fix the problem.
8. Run `xcode-select --install` from the command line (see <https://stackoverflow.com/questions/50229781/package-installation-in-r-fail-on-macos>).
9. Run `brew install libxml2`.
10. Re-launch RStudio, re-run `install.packages("tidyverse")` - installs `xml2` and then tells me `tidyverse` is installed. (Warns me that `default/America/Toronto` is an unknown timezone, but I can live with that...)
11. `library(tidyverse)` does what <http://r4ds.had.co.nz/data-visualisation.html> tells me I should expect.

See also #70 (maybe?).

**Comment by batpigandme** [comment]
>Uninstall all versions of R and RStudio from MacBook Air.
> ...
> Install RStudio 1.1.456.
> which r from command line finds nothing (so I believe there are no conflicting version of R in play).

I realize this sounds absurd, but I thought you had to install R at some point before installing RStudio.

That aside, the libxml2 problem is definitely one I've run into before, though.  Do you run into the same problem trying to install [xml2](https://github.com/r-lib/xml2) in a empty R installation? Just trying to figure out if it's localised to the tidyverse meta-package (this), or if it has something to do with the xml2 dependency outside of tidyverse.

There have been a few threads on community with xml2 installation troubles, e.g.
* https://community.rstudio.com/t/xml2-package-installation-issues-pkg-config-path-help/10319/3?u=mara
* https://community.rstudio.com/t/download-data-from-website-into-rstudio/2345/19?u=mara

**Comment by gvwilson** [comment]
1. I thought I had to install R before RStudio, but apparently that's not (or no longer?) true. `which r` on my Mac still comes up empty - how do I check the path to the R executable from within RStudio?
2. Just got my company laptop, so I'll try installing there and see what happens - if I understand correctly, I should `brew install r` and then run R from the command line and run `install.package('xml2')` ?
Thanks!

**Comment by gvwilson** [comment]
1. `R.home()` reports `/Library/Frameworks/R.framework/Resources`, which isn't in my `PATH` - I must have installed R via the r-project.org installer at some point (?).
2. Installing RStudio on my new company laptop -> can't find R, so @batpigandme was right - it needs separate installation.

**Comment by apreshill** [comment]
For posterity, I ran into the same issue and by sheer luck I was sitting with @jimhester and figured out the source of my problem quickly. So for future people stumbling upon this thread, if you are using a new computer with High Sierra or Mojave and would like to install R fresh, you'll likely run into this same error as @gvwilson if you used Homebrew `brew` to install R as in:

`$ brew install r`

I did this via a Homebrew Brewfile, and it was the source of my `xml2` problem. So first I undid that install using:

`$ brew uninstall r`

This means I was OK with torching all my installed packages, because I was on a new computer I was OK with this!

Then I used Homebrew to install the `r-app` via cask:

`$ brew cask install r-app`

After doing that, I was able to install the `tidyverse` package (and all my other packages) without problems.

My updated Brewfile then looked like this:

```
tap 'homebrew/cask'
cask 'r-app'
```

**Comment by naupaka** [comment]
I have also found that if you are using anaconda it will screw up libxml2 (and occasionally some other things) for R. In the past I was able to get around this with `$ conda deactivate` then `R> install.packages() that need XML2` then `$ conda activate base` (or whatever your env of choice is). I also just happened upon the suggestion @apreshill mentioned, and it helps a lot with problems like this, because now you can install the precompiled package binaries from CRAN instead of having to compile them yourself.

**Comment by hadley** [comment]
I think the basic advice is __NEVER INSTALL R FROM BREW__ (unless you really know what you are doing).

**Comment by kozakjefferson** [comment]
> I have also found that if you are using anaconda it will screw up libxml2 (and occasionally some other things) for R. In the past I was able to get around this with `$ conda deactivate` then `R> install.packages() that need XML2` then `$ conda activate base` (or whatever your env of choice is). I also just happened upon the suggestion @apreshill mentioned, and it helps a lot with problems like this, because now you can install the precompiled package binaries from CRAN instead of having to compile them yourself.
Thank you very much, I've never tough about conda screw up..

**Comment by JessicaGreben** [comment]
This stackoverflow answer worked for me: https://stackoverflow.com/a/50252325
