### ISSUE TITLE
Attach lubridate

### ISSUE THREAD

**Issue by hammer** [tidyverse/tidyverse#157]
From @hadley on the [RStudio Discourse](https://community.rstudio.com/t/what-is-the-core-tidyverse-packages/3628/7?u=hammer) in January 2018:

> The real question is why isn’t lubridate in core? The answer is that it currently conflicts (in a narrow sense) with too many base functions - in practice the lubridate functions extend or wrap the base alternatives so the conflict aren’t harmful in practice, but I haven’t had time to think through how this should be indicated in the tidyverse loading screen.

Figured I'd file an issue on GitHub in case there's any loading screen progress to track (that could perhaps be linked to this issue).

**Comment by hadley** [comment]
This has two components:

* dplyr and lubridate need to share the same definition of `union`, `intersect` and `setdiff`: https://github.com/tidyverse/lubridate/issues/693

* tidyverse needs to use the [conflicted](https://conflicted.r-lib.org) package instead of the current report: #135. This is a fairly big change so I want a bit more time for conflicted in the wild before introducing it.

**Comment by mdancho84** [comment]
I second this request: `lubridate` is critical for working with `date` and `datetime` just as `stringr` is essential for working with `chr` and `forcats` is for `fct`. This would be a good change for many people that routinely work with timestamp data.

**Comment by batpigandme** [comment]
@PAMorin this is off-topic for this issue, since the thread is about whether or not lubridate should be added to the core tidyverse packages (i.e. attached when `library(tidyverse)` is run).

Could you please ask over on [community.rstudio.com](https://community.rstudio.com/)?

**Comment by hadley** [comment]
* [ ] https://github.com/tidyverse/lubridate/issues/705
* [ ] https://github.com/tidyverse/lubridate/issues/693
