### ISSUE TITLE
ERROR: dependencies ‘broom’, ‘dplyr’, ‘dbplyr’, ‘httr’, ‘modelr’, ‘rvest’, ‘tidyr’, ‘xml2’ are not available for package ‘tidyverse’

### ISSUE THREAD

**Issue by christa88** [tidyverse/tidyverse#163]
I need to download EdgeR. Having issues with downloading packages. One package install.packages("dplyr", dependencies = TRUE) will not download so tried install.packages("tidyverse"). I am getting the following error: ERROR: dependencies ‘broom’, ‘dplyr’, ‘dbplyr’, ‘httr’, ‘modelr’, ‘rvest’, ‘tidyr’, ‘xml2’ are not available for package ‘tidyverse’. Warning in install.packages : installation of package ‘tidyverse’ had non-zero exit status.

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.) It sounds like the dependencies weren't installed (clearly), but in order to help you troubleshoot, basic system information, and full error messages will be helpful.
