### ISSUE TITLE
tidyverse_rlang error

### ISSUE THREAD

**Issue by DataXujing** [tidyverse/tidyverse#164]
Error in filter_impl(.data, quo) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.

**Comment by batpigandme** [comment]
Since the tidyverse is a meta package, it's best to file issues in the specific package that's resulting in the error. I'm happy to move it for you, but in order to get this sorted, we'll need some more information. 

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by yutannihilation** [comment]
You need to update dplyr. See https://github.com/tidyverse/dplyr/issues/3941
