### ISSUE TITLE
condensed summary illegible in colour scheme Tomorrow Night 80s

### ISSUE THREAD

**Issue by arne1921KF** [tidyverse/tidyverse#169]
The colour scheme chosen for the condensed summary of conflicts has a slight conflict with the R-Studio color scheme *Tomorrow Night 80s*. 

Not sure if this qualifies as an issue, but a fix would be appreciated.

![tidyverse_colscheme_tomorrownight80s](https://user-images.githubusercontent.com/27221713/52407166-c7c9d180-2acf-11e9-9903-15a36d47a1ba.jpg)

**Comment by jennybc** [comment]
Possible related to https://github.com/rstudio/rstudio/issues/1959

**Comment by batpigandme** [comment]
What version of RStudio are you using? I had this problem at one point with a custom theme not registering that it was a "dark" theme, but it was fixed in a later build — it should shift to a different color when it registers that the bgColor is dark.
![image](https://user-images.githubusercontent.com/831732/52478919-ea61f600-2b74-11e9-903e-d1d146d26c8f.png)

**Comment by batpigandme** [comment]
Since it looks like this was a theming issue fixed in the IDE, I'm going to go ahead and close this.

**Comment by arne1921KF** [comment]
Im using RStudio 1.1.456. Will as our support to push the latest version to our software distribution center and check. Thanks.

**Comment by batpigandme** [comment]
Yeah, 1.2 is still preview, but its release is pretty imminent, I believe.
