### ISSUE TITLE
Error on Tibble package

### ISSUE THREAD

**Issue by SinfantiHU** [tidyverse/tidyverse#181]
i am trying to knit a project and i keep getting this message at line 29

Error: (converted from warning) package 'tibble' is in use and will not be installed.

This is line 29...
if(!requireNamespace("devtools")) install.packages("devtools")

I have tried uninstalling and reinstalling tibble ( id dnot uninstall and reinstall tidyverse or tidyr or dplyr)   

Arghhh

**Comment by batpigandme** [comment]
The tidyverse package is a meta-package, so we try to put issues in the repos for the specific packages (e.g. this would go in https://github.com/tidyverse/tibble/issues ). However, in order to troubleshoot this, it'll be helpful to have a small reproducible example (i.e. a [reprex](https://reprex.tidyverse.org/)). To start, you might want to make a reprex, and then open a thread on community.rstudio.com . If it turns out that there's an actual bug, we can always open a new issue in tibble, or the appropriate package.

**Comment by SinfantiHU** [comment]
i solved the issue.
