### ISSUE TITLE
unable to get pdf from rmarkdown

### ISSUE THREAD

**Issue by sharmasapna** [tidyverse/tidyverse#217]
! Package inputenc Error: Unicode character ─ (U+2500)
(inputenc)                not set up for use with LaTeX.

---
unable to get pdf from rmarkdown
I have installed the latest version of tinytex
tried with all engines pdlaftex,xelatex,lualatex

```r
# insert reprex here
library("tidyverse")
```

**Comment by batpigandme** [comment]
Hi Sapna,

Unless I'm missing something, it sounds like you're having issues with https://github.com/rstudio/rmarkdown, as opposed to the tidyverse package. Either way, this sort of question is a better fit for https://community.rstudio.com than for GitHub, since it doesn't sound like a bug or a feature request. Do you mind asking it over there? (If it _does_ turn out to be a bug, discussing it there will help generate a more informative issue to file in the appropriate repo).

In this case, some system information (operating system, versions of R, RStudio, etc) would probably be helpful for troubleshooting, too.
