### ISSUE TITLE
Problem with instalation tidyverse on Mac

### ISSUE THREAD

**Issue by Vratik** [tidyverse/tidyverse#233]
ERROR: configuration failed for package ‘xml2’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/xml2’
Warning in install.packages :
  installation of package ‘xml2’ had non-zero exit status

**Comment by batpigandme** [comment]
This looks like an issue with your installation of xml2 (which is a library the tidyverse package depends on). This sort of question is usually a better fit for [community.rstudio.com](community.rstudio.com), would you mind asking over there? It will help if you can include some system details (e.g. what operating system are you running, did you try to compile from source, etc.) 

If it turns out to be a bug in xml2 itself, we can then open an issue in that repo. 

Thanks
