### ISSUE TITLE
install (tidyverse) problem Rstudio  4.2.1

### ISSUE THREAD

**Issue by Larryriver6** [tidyverse/tidyverse#318]
# RStudio
In R 2.1.0 packages "tidyverse" can¨t operate
# insert reprex here

**Comment by batpigandme** [comment]
The tidyverse depends on you having R >= 3.3.

**Comment by batpigandme** [comment]
I'm going to close #317 since you seem to have posted this twice. I can't tell from your title vs. the body of your issue if you're using R 4.2.1 or R 2.1.0 (the version of R is printed in the console when you first load R, you can also get it by runnning `sessionInfo()`).

If you're running R version 2.1.0, it is too old and unsupported by the tidyverse. You can read more about [R version support in the tidyverse](https://www.tidyverse.org/blog/2019/04/r-version-support/) in the linked blog post.

If you're using R version 4.2.1 and getting a message about R 2.1.0, I'd venture a guess that you're trying to use packages/libraries that were built with an old version of R, which won't work. You need to reinstall them with major R version changes. This post, [Major R Updates (Where Are My Packages?)](https://bookdown.org/pdr_higgins/rmrwr/major-r-updates-where-are-my-packages.html) has a nice description of when and how to update/reinstall packages when your R version is updated (R 2.1.0 is from 2005, so I can't imagine that's actually what you're running).

If you can give more details, hopefully we can get this issue resolved for you.
