### ISSUE TITLE
Unable to knit .Rmd to PDF after updating to tidyverse 2.0.0

### ISSUE THREAD

**Issue by bleds22e** [tidyverse/tidyverse#327]
I am unable to knit .Rmd files to PDF after installing `tidyverse 2.0.0` I uninstalled 2.0.0, reinstalled 1.3.0, and everything works fine. The error seems to be in the newly added line about the conflicted package.

Mac, Ventura 13.2.1
R version 4.2.2
RStudio Version 2022.12.0+353 (2022.12.0+353)

The error I got with pdfLaTeX was the following:
! LaTeX Error: Unicode character ^^[ (U+001B)
               not set up for use with LaTeX.

When I changed to XeLaTeX, the error was:
! Text line contains an invalid character.
l.129 ## i Use the ^^[
                                     ]8;;http://conficted.r-lib.org/^^Gconflicted package^...

Suppressing the message in the code chunk did not solve the issue.

I'm new to using the reprex package, but I tried! Unfortunately, but reprex_render() kept crashing R, presumably due to the error above.
[test.log](https://github.com/tidyverse/tidyverse/files/10996544/test.log)
[test.knit.md](https://github.com/tidyverse/tidyverse/files/10996546/test.knit.md)

**Comment by batpigandme** [comment]
Can confirm error re. escape character (`! LaTeX Error: Unicode character ^^[ (U+001B)`) using tinytex:

source input `test-issue327.Rmd` (recreated below):
````
---
title: "Test"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```
````

Output from render after updating tinytex with `tinytex::tlmgr_update()` per recommendations at https://yihui.org/tinytex/r/#debugging:
```
  |.....................                               |  40% (setup)          

processing file: test-issue327.Rmd
                                                                                                            
/opt/homebrew/bin/pandoc +RTS -K512m -RTS test-issue327.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output test-issue327.tex --lua-filter /Users/maraaverick/Library/R/arm64/4.2/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Users/maraaverick/Library/R/arm64/4.2/library/rmarkdown/rmarkdown/lua/latex-div.lua --embed-resources --standalone --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' 
output file: test-issue327.knit.md

Backtrace:
    x
 1. \-rmarkdown::render(...)
 2.   \-rmarkdown:::latexmk(...)
 3.     \-tinytex::latexmk(file, engine, if (biblatex) "biber" else "bibtex")
 4.       \-tinytex:::latexmk_emu(...)
 5.         \-tinytex (local) run_engine()
 6.           +-tinytex:::system2_quiet(...)
 7.           \-tinytex (local) on_error()
 8.             \-tinytex:::show_latex_error(file, logfile)
! LaTeX Error: Unicode character ^^[ (U+001B)
               not set up for use with LaTeX.

Error: LaTeX failed to compile test-issue327.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test-issue327.log for more info.
Execution halted
```

With `options(tinytex.verbose = TRUE)`:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
I was unable to find any missing LaTeX packages from the error log test-issue327.log.
Backtrace:
    x
 1. \-rmarkdown::render(...)
 2.   \-rmarkdown:::latexmk(...)
 3.     \-tinytex::latexmk(file, engine, if (biblatex) "biber" else "bibtex")
 4.       \-tinytex:::latexmk_emu(...)
 5.         \-tinytex (local) run_engine()
 6.           +-tinytex:::system2_quiet(...)
 7.           \-tinytex (local) on_error()
 8.             \-tinytex:::show_latex_error(file, logfile)
! LaTeX Error: Unicode character ^^[ (U+001B)
               not set up for use with LaTeX.

Error: LaTeX failed to compile test-issue327.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test-issue327.log for more info.
Execution halted
```

I'm not sure how you tracked down that the issue lies with conflicted (though I have no reason to believe otherwise). Everything knits fine with, say, `library(dplyr)`, in place of `library(tidyverse)`.

I *_am_* able to knit the file with messages and warnings turned off for the chunk with `library(tidyverse)` (or with just `message=FALSE`). Below knits to PDF fine:
````
---
title: "Test"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```
````

Might it be struggling with the message meant to be printed only when the tidyverse is loaded interactively?

@bleds22e, could you try knitting with message turned off after a tinytex update?

**Comment by bleds22e** [comment]
@batpigandme when I use `message = FALSE` in the code chunk, it does work! 

But I shouldn't have to put that to be able to knit something...

**Comment by jttoivon** [comment]
This is quite annoying. I have to hand-edit the tex file after each knit. I hope this will be fixed soon.

**Comment by hadley** [comment]
Two work arounds in the meantime:

* Install the dev version of cli: `pak::pak("r-lib/cli")`
* Suppress the tidyverse loading message everywhere by adding this to your `.Rprofile`: `options(tidyverse.quiet = TRUE)`
