### ISSUE TITLE
issue with group_by function

### ISSUE THREAD

**Issue by tib-sim** [tidyverse/tidyverse#328]
Hi - I have an issue with ```tidyverse``` and the ```group_by function```.
This error appears totally randomly. Basically in the example below ds_mean will just return one value like if it was calculating the average of all my data point without considering the three factors inserted in group_by.
I was wondering if it coud be a version issue but after having updating R and Rstudio I have the same issue.
Actually I can solve the issue if I save the ds in csv file and upload it (after restarting R studio) and then run the same command lines than below. I sounds like the issue happens if the code is long and I am using the ```group_by function``` multiple times. This is a very weird and annoying issue that I cannot see how to solve it so far (besides saving a csv file and restarting R studio).

```r
ds_mean=ds%>%
 group_by(Subj,Condition, Subgroup)%>%
 summarise(y_mean=mean(y_mean))
```

**Comment by batpigandme** [comment]
This question is better suited to the [community site](https://community.rstudio.com) where folks can help you figure out if it's actually a bug in the package (which, in this case, would actually be dplyr, since it's the source of `group_by()`—tidyverse is just a wrapper package). If it turns out it _is_ a bug, we can open an issue there, but if you could ask on community first, that would be great.

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

```r
install.packages("reprex")
```
If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

There's a nice FAQ on how to do a minimal reprex for beginners, below:

https://community.rstudio.com/t/faq-how-to-do-a-minimal-reproducible-example-reprex-for-beginners/23061?u=mara

For pointers specific to the community site, check out the [reprex FAQ](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219).
