### ISSUE TITLE
Could scales also be loaded within `library(tidyverse)`? 

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/tidyverse#340]
scales is crucial when using ggplot2

It would be awesome if could be automatically loaded as part of the tidyverse within `library(tidyverse)`

**Comment by hadley** [comment]
Making a change to the loaded packages is a big deal because it might create new conflicts with other loaded packages. And within the tidyverse, it creates two:

```
✖ readr::col_factor() masks scales::col_factor()
✖ purrr::discard()    masks scales::discard()
```

So to even begin this process, scales would need to deprecate the `col_factor()` and `discard()` functions. 

But I don't think the payoff is likely to be worth the effort, especially since the ggplot2/scales split has existed for so long and doesn't seem to cause _that_ many problems.

**Comment by davidhodge931** [comment]
`scales::discard` is already deprecated.

So just col_factor to deal with.. It could be renamed to `scales::col_category` or `col_character`.

But appreciate this stuff is a pain. Thanks for all the {tidyverse} etc work
