### ISSUE TITLE
Depends vs Imports in DESCRIPTION

### ISSUE THREAD

**Issue by holgerbrandl** [tidyverse/tidyverse#40]
Why isn't tidyverse declaring "Depends" and "Imports" in its DESCRIPTION in the typical way as of
>The main difference is that where Imports just loads the package, Depends attaches it. 
[Source](http://r-pkgs.had.co.nz/namespace.html)

Currently in tidyverse nothing is tagged as "Depends" even if it attaches 8 packages to the global namespace:
```
library(tools)
package_dependencies("tidyverse", which="Imports")
package_dependencies("tidyverse", which="Depends")

require(tidyverse)
sessionInfo()
> ...
> other attached packages:
> [1] magrittr_1.5     stringr_1.1.0    dplyr_0.5.0      purrr_0.2.2.9000
> [5] readr_1.0.0      tidyr_0.6.1      tibble_1.2       ggplot2_2.2.1
> [9] tidyverse_1.1.1
> ...
```
I'm not really a packaging expert, but I'd somehow expect all those packages (except no9 for sure) to show up under "Depends" in the DESCRIPTION.

**Comment by hadley** [comment]
It's complicated 😉

**Comment by MichaelChirico** [comment]
@hadley could you elaborate 😄 

We are facing the issue here:

https://github.com/r-lib/lintr/issues/1127

That `lintr::object_usage_linter` basically has no way of working for scripts that run `library(tidyverse)` but nothing else. It seems to me the "core" packages are pretty straightforwardly Depends, per WRE:

> The ‘Depends’ field gives a comma-separated list of... packages [which] will be attached before the current package when library or require is called.

Here's `library` being called in `.onAttach`:

https://github.com/tidyverse/tidyverse/blob/6186fbf09bf359110f8800ff989cbbdd40485eb0/R/attach.R#L10-L16

Barring tidyverse listing core packages in `Depends`, I'm not sure how to fix the lintr issue besides a carveout for `tidyverse` that we'd then have to maintain. Open to ideas though.

**Comment by hadley** [comment]
I can no longer remember the exact motivation, but it's highly likely that I wanted greater control over the printed appearance and handling of conflicts. I'm not sure whether I'd do the same today, as I also needed to add a special carve out to downlit for similar reasons: https://github.com/r-lib/downlit/blob/02779cde4dbaa15521eaa108b931049b857d7f53/R/packages.R#L32-L41

**Comment by MichaelChirico** [comment]
Does that mean we could consider moving to Depends?

I keep coming back to this... tidyverse really is alone in "misusing" the Imports field like it does.

**Comment by hadley** [comment]
@MichaelChirico I don't think so. It's definitely an abuse, but I still can't see another way to achieve the precise UI that I want.

**Comment by MichaelChirico** [comment]
> the precise UI that I want.

It would help to elaborate on this to see what the issue is in case anyone sufficiently motivated wanted to pitch in -- I'm having trouble imagining something that can't be addressed by appropriate `.onLoad()`/`.onAttach()` hooks

**Comment by hadley** [comment]
I tried pretty hard at the time, so I'm sceptical that's worthwhile to write a precise spec so that someone else could have a go.
