### ISSUE TITLE
library(tidyverse) fails on pre-1.1 versions of RStudio due to lack of getThemeInfo

### ISSUE THREAD

**Issue by nicknimchuk** [tidyverse/tidyverse#83]
When loading the tidyverse with `library(tidyverse)` in RStudio 1.0.153, the following error occurs:
```
Error: package or namespace load failed for ‘tidyverse’:
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: NULL
  error: Function getThemeInfo not found in RStudio
```
Working backwards, the error occurs in `text_col` when it calls `getThemeInfo`. The function checks to ensure that `rstudioapi` is available, but not whether the version in use has `getThemeInfo` available. This can be isolated as:
```r
tidyverse:::text_col("Hi")
# Error: Function getThemeInfo not found in RStudio
```
Running the command on the same computer in the latest release of RStudio does not generate an error.

**Comment by tiernanmartin** [comment]
I'm experiencing the same error using RStudio Server v.1.1.355

**Comment by tiernanmartin** [comment]
This fixed it for me:
```r
install.packages("crayon")
```
As suggested [here](https://community.rstudio.com/t/tidyverse-installation-problems/2634/6?u=tiernan)

**Comment by hadley** [comment]
@tiernanmartin I think that's a different problem, but it's also fix in the dev version

**Comment by JackBoult** [comment]
After:
install.packages("tidyverse")
tidyverse   1.1.1   1.2.1             FALSE
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.4/bin/x64/R" CMD INSTALL -l "C:\Users\User\Documents\R\win-library\3.2" C:\Users\User\AppData\Local\Temp\RtmpGQjwZM/downloaded_packages/tidyverse_1.2.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

I get:
> library(tidyverse)
Error in library(tidyverse) : there is no package called ‘tidyverse’

...this problem is only on my home laptop (my work computer runs the same code fine).

What is going on?

**Comment by BrownAlpine** [comment]
hi, Rstudio Version 1.1.423

After installing R3.4.4 (2018-03-15) I have a similar problem, I get this:
library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
there is no package called ‘tidyr’"

Rstudio Version 1.1.423
